### ISSUE TITLE
null pointer exception in Controller

### ISSUE THREAD

**Issue by prbaron** [ESIR3-NSOC/NSOC-2011#1]
There is a JavaNullPointerException in Control Class, line 139.

Original test : 
- urls sent to the server : 
       - @ip:818/b7/s930 (it means get all datatypes value)
       - @ip:8182/b7/s930/temperature/01-02-2012/02-03-2012 (it means get all values of temperature from 1st February 2012 to 2nd March 2012).
- the Server send a HmiRequest to the Controller.

**Comment by aesnaux** [comment]
Contol depends of dataCtrl component to have some data. You just have to add this component.
